### ISSUE TITLE
additional option: outcross items instead of delete

### ISSUE THREAD

**Issue by paulle** [Abrynos/ShoppingList#40]
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

To outcross items gives sometimes a better overview what's buyed and what one have to buy.

### Solution

An additional option for outcrossing items

### Why are the currently avialable solutions not sufficient?

This option is till now not available

### Can you help us with this feature request?

Somehow, I can test and offer feedback, but I can't code the solution.

**Comment by Abrynos** [comment]
In general the idea is not bad, because you can re-use items that you buy a lot on a regular basis. However I'm not sure whether (and if, how) to implement it.

- Adding a fourth button in addition to the plus, minus and trashcan is not an option, as the buttons would then use up too much space on some phones and leave only a tiny bit of screen space for the text.
- Adding an option to replace the trashcan with a button to cross stuff out seems to be a hassle when you have items you don't need regularly and just want to buy once. Then you have to go to the options to switch back to deletion, delete the item(s) and once again switch the option for your "normal mode" to continue crossing out.

If you have other ideas/thoughts on the topic, please let me know.

**Comment by paulle** [comment]
What do you think, hitting the trashcan button opens two possibilities: delete or crossout

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
Another option. Put a checkbox before each item, when the checkbox is hit, the item get outcrossed. Or the checkbox only and the user sees at one glance if the checkbox is activated or not.

**Comment by Abrynos** [comment]
> hitting the trashcan button opens two possibilities: delete or crossout

Theoretically possible, but there is two options to do this:
- Have a setting choosing which one is done when hitting the trashcan; This has the previously mentioned disadvantage when having both regular and one-time items in your list
- Open some form of modal/pop-up and let the user choose for each and every item; This complicates the workflow immensely

> Put a checkbox before each item

This has the same problem as adding another icon at the end of the line. It uses too much space and leaves only a tiny bit of space for the actual text.


The more I think about implementing this idea, even tho practical in theory, the less I like adding it to the app. Thank you very much for your input tho.

**Comment by paulle** [comment]
Another option, long press on a item will give te possibility to cross it out.
